openapi: '3.1.0'
info:
  version: '1.0.0'
  title: 'Poker Outcome Tracker'
  description: Users can track their gains/losses in poker using this API

paths:
  /auth/verify:
    post:
      summary: Verify your email
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
      responses:
        '202':
          description: A verification code was sent to the provided email address

  /auth/register:
    post:
      summary: Register a player with verified email address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterPlayerRequest'
      responses:
        '201':
          description: A player was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '400':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /players/{playerId}:
    parameters:
      - $ref: '#/components/parameters/PlayerId'
    get:
      summary: Read a player
      responses:
        '200':
          description: The player corresponding to the provided playerId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '404':
          description: The player with the corresponding playerId was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a player
      responses:
        '204':
          description: The player with the corresponding playerId was deleted

  /players/{playerId}/games:
    parameters:
      - $ref: '#/components/parameters/PlayerId'
    get:
      summary: Get game history of a player
      responses:
        '200':
          description: A list of recent games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
        '404':
          description: The player with the corresponding playerID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /games:
    post:
      summary: Create a game
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameRequest'
      responses:
        '201':
          description: The game was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Failed to create the game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /games/{gameId}:
    parameters:
      - $ref: '#/components/parameters/GameId'
    get:
      summary: Read a game
      responses:
        '200':
          description: The game corresponding to the provided gameId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: The game corresponding to the provided gameId does not exist

components:
  parameters:
    PlayerId:
      name: playerId
      description: The unique identifier of a player
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/PlayerId'

    GameId:
      name: gameId
      description: The unique identifier of a game
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/GameId'

  schemas:
    PlayerId:
      description: The unique identifier of a player
      type: string
      format: uuid

    PlayerName:
      description: The username of a player
      type: string

    PlayerEmail:
      description: The email of a player
      type: string
      format: email

    Otp:
      type: string

    Player:
      type: object
      required:
        - playerId
        - playerName
        - playerEmail
      properties:
        playerId:
          $ref: '#/components/schemas/PlayerId'
        playerName:
          $ref: '#/components/schemas/PlayerName'
        playerEmail:
          $ref: '#/components/schemas/PlayerEmail'

    VerifyEmailRequest:
      type: object
      required:
        - playerEmail
      properties:
        playerEmail:
          $ref: '#/components/schemas/PlayerEmail'

    RegisterPlayerRequest:
      type: object
      required:
        - playerName
        - playerEmail
        - otp
      properties:
        playerName:
          $ref: '#/components/schemas/PlayerName'
        playerEmail:
          $ref: '#/components/schemas/PlayerEmail'
        otp:
          $ref: '#/components/schemas/Otp'

    GameId:
      description: The unique identifier of a game
      type: string
      format: uuid

    PlayedAt:
      description: A game's timestamp
      type: string
      format: date-time

    Game:
      type: object
      required:
        - gameId
        - playedAt
        - authorId
      properties:
        gameId:
          $ref: "#/components/schemas/GameId"
        playedAt:
          $ref: '#/components/schemas/PlayedAt'
        authorId:
          $ref: '#/components/schemas/PlayerId'
        participations:
          type: array
          items:
            $ref: '#/components/schemas/Participation'

    CreateGameRequest:
      description: Record a game
      type: object
      required:
        - playedAt
        - authorId
        - participations
      properties:
        playedAt:
          $ref: '#/components/schemas/PlayedAt'
        authorId:
          $ref: '#/components/schemas/PlayerId'
        participations:
          type: array
          items:
            $ref: '#/components/schemas/Participation'

    Participation:
      type: object
      required:
        - playerId
        - buyIn
        - finalStack
      properties:
        playerId:
          $ref: '#/components/schemas/PlayerId'
        buyIn:
          type: integer
        finalStack:
          type: integer

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string